"use client";

import { Suspense, useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  CheckCircle2, Circle, Loader2, ArrowRight, Save,
  User, Users, Sparkles, Plus, X, Trash2,
} from "lucide-react";
import { useSessionDetail } from "@/lib/supabase/hooks";
import { addConsultantNote, saveSessionOutput, finalizeSession } from "@/lib/supabase/queries";
import type { TaskItem } from "@/types";

function generateId(): string {
  return `task_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
}

const TASK_PRESETS = {
  client: [
    "Provide additional context on business objective",
    "Clarify data definitions for key fields",
    "Review and validate initial findings",
    "Grant access to additional data sources",
    "Confirm priority areas for deeper analysis",
    "Schedule a findings review meeting",
  ],
  internal: [
    "Perform deeper statistical analysis",
    "Build predictive model for key outcome",
    "Create data quality monitoring dashboard",
    "Conduct root cause analysis on flags",
    "Prepare presentation for client review",
    "Document methodology and assumptions",
  ],
};

function NextStepsInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const sessionId = searchParams.get("sessionId") ?? "";
  const { data, loading, refetch } = useSessionDetail(sessionId);
  const [tasks, setTasks] = useState<TaskItem[]>([]);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [showPresets, setShowPresets] = useState<"client" | "internal" | null>(null);
  const [newTaskText, setNewTaskText] = useState("");
  const [newTaskType, setNewTaskType] = useState<"client" | "internal">("client");

  useEffect(() => {
    if (data?.output?.tasks && data.output.tasks.length > 0) {
      setTasks(data.output.tasks);
    }
  }, [data]);

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <Loader2 className="w-6 h-6 text-primary animate-spin" />
      </div>
    );
  }

  const session = data?.session;
  const output = data?.output;
  const client = data?.client;

  if (!session || !output) {
    return (
      <div className="p-8">
        <p className="text-sm text-muted-foreground">No session data found.</p>
      </div>
    );
  }

  const clientTasks = tasks.filter((t) => t.type === "client");
  const internalTasks = tasks.filter((t) => t.type === "internal");
  const clientDone = clientTasks.filter((t) => t.done).length;
  const internalDone = internalTasks.filter((t) => t.done).length;

  const toggleTask = (taskId: string) => {
    setTasks((prev) =>
      prev.map((t) => (t.id === taskId ? { ...t, done: !t.done } : t))
    );
  };

  const deleteTask = (taskId: string) => {
    setTasks((prev) => prev.filter((t) => t.id !== taskId));
  };

  const addTask = (text: string, type: "client" | "internal") => {
    if (!text.trim()) return;
    setTasks((prev) => [
      ...prev,
      { id: generateId(), text: text.trim(), type, done: false, autoGenerated: false },
    ]);
    setNewTaskText("");
  };

  const addPreset = (text: string, type: "client" | "internal") => {
    setTasks((prev) => [
      ...prev,
      { id: generateId(), text, type, done: false, autoGenerated: false },
    ]);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveSessionOutput(sessionId, {
        execSummary: output.execSummary,
        keySignals: output.keySignals,
        dataQualityFlags: output.dataQualityFlags,
        recommendedAnalyses: output.recommendedAnalyses,
        followUpQuestions: output.followUpQuestions,
        assumptions: output.assumptions,
        confidenceScore: output.confidenceScore,
        dataCompleteness: output.dataCompleteness,
        statSummary: output.statSummary ?? null,
        tasks,
      });
      await finalizeSession(sessionId, "complete");
      if (tasks.length > 0) {
        await addConsultantNote(
          sessionId,
          `Next steps saved: ${clientDone + internalDone}/${tasks.length} tasks (${clientDone}/${clientTasks.length} client, ${internalDone}/${internalTasks.length} internal)`
        );
      }
      setSaved(true);
    } catch (e) {
      console.error("Failed to save tasks", e);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="p-8">
      <div className="mb-7">
        <div className="flex items-center gap-2 text-xs text-muted-foreground mb-2 font-mono">
          <span>{client?.name ?? "Client"}</span>
          <span className="text-muted-foreground/50 mx-1">/</span>
          <span className="text-foreground">{session.title}</span>
        </div>
        <h1
          className="text-2xl font-semibold text-foreground"
          style={{ fontFamily: "var(--font-lora), serif" }}
        >
          Next Steps
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Define and assign tasks — for the client and for the internal team. Track progress across sessions.
        </p>
      </div>

      {/* Summary bar */}
      <div className="flex items-center gap-4 mb-6 text-xs font-mono">
        <div className="flex items-center gap-1.5 bg-card border border-border rounded-xl px-3.5 py-2">
          <User className="w-3.5 h-3.5 text-primary" />
          <span>Client: {clientDone}/{clientTasks.length}</span>
        </div>
        <div className="flex items-center gap-1.5 bg-card border border-border rounded-xl px-3.5 py-2">
          <Users className="w-3.5 h-3.5 text-[#7A9E9E]" />
          <span>Internal: {internalDone}/{internalTasks.length}</span>
        </div>
        <div className="flex items-center gap-1.5 bg-card border border-border rounded-xl px-3.5 py-2">
          <Sparkles className="w-3.5 h-3.5 text-muted-foreground" />
          <span>Total: {clientDone + internalDone}/{tasks.length}</span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6 mb-8">
        {/* Client column */}
        <div className="bg-card border border-border rounded-[14px] p-5">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-accent flex items-center justify-center">
                <User className="w-3.5 h-3.5 text-primary" />
              </div>
              <span className="text-xs font-semibold text-foreground uppercase tracking-wider font-mono">For the Client</span>
            </div>
            <span className="text-[10px] font-mono text-muted-foreground">{clientDone}/{clientTasks.length}</span>
          </div>

          <div className="space-y-1.5 mb-3">
            {clientTasks.map((task) => (
              <div
                key={task.id}
                className={`group flex items-start gap-2.5 p-2.5 rounded-xl transition-colors ${
                  task.done ? "bg-emerald-50/50" : "hover:bg-muted/40"
                }`}
              >
                <button onClick={() => toggleTask(task.id)} className="flex-shrink-0 mt-0.5">
                  {task.done ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  ) : (
                    <Circle className="w-4 h-4 text-muted-foreground/40 hover:text-primary transition-colors" />
                  )}
                </button>
                <span
                  className={`flex-1 text-xs leading-relaxed ${
                    task.done ? "text-muted-foreground line-through" : "text-foreground"
                  }`}
                >
                  {task.text}
                  {task.autoGenerated && (
                    <span className="ml-1.5 text-[9px] font-mono text-muted-foreground/50">(auto)</span>
                  )}
                </span>
                <button
                  onClick={() => deleteTask(task.id)}
                  className="opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0 p-0.5 rounded hover:bg-red-50"
                >
                  <Trash2 className="w-3 h-3 text-muted-foreground hover:text-red-500" />
                </button>
              </div>
            ))}
            {clientTasks.length === 0 && (
              <p className="text-xs text-muted-foreground text-center py-4">No client tasks yet. Add one below.</p>
            )}
          </div>

          {/* Add client task */}
          <div className="border-t border-border pt-3 mt-1">
            <div className="flex gap-1.5 mb-1.5">
              <input
                value={newTaskType === "client" ? newTaskText : ""}
                onChange={(e) => { setNewTaskType("client"); setNewTaskText(e.target.value); }}
                onKeyDown={(e) => { if (e.key === "Enter") addTask(newTaskText, "client"); }}
                placeholder="Add task…"
                className="flex-1 bg-input-background border border-border rounded-lg px-2.5 py-1.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
              <button
                onClick={() => addTask(newTaskText, "client")}
                disabled={!newTaskText.trim() || newTaskType !== "client"}
                className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-medium bg-primary text-primary-foreground hover:bg-primary/90 disabled:bg-muted disabled:text-muted-foreground transition-colors"
              >
                <Plus className="w-3 h-3" />
              </button>
            </div>
            <button
              onClick={() => setShowPresets(showPresets === "client" ? null : "client")}
              className="text-[10px] font-mono text-muted-foreground hover:text-foreground transition-colors"
            >
              {showPresets === "client" ? "Hide suggestions" : "Suggestions"}
            </button>
            {showPresets === "client" && (
              <div className="flex flex-wrap gap-1 mt-2">
                {TASK_PRESETS.client.map((preset) => (
                  <button
                    key={preset}
                    onClick={() => addPreset(preset, "client")}
                    className="text-[10px] px-2 py-1 rounded-lg bg-muted text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors"
                  >
                    + {preset.length > 30 ? preset.slice(0, 30) + "…" : preset}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Internal column */}
        <div className="bg-card border border-border rounded-[14px] p-5">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-[#7A9E9E]/20 flex items-center justify-center">
                <Users className="w-3.5 h-3.5 text-[#7A9E9E]" />
              </div>
              <span className="text-xs font-semibold text-foreground uppercase tracking-wider font-mono">For the Internal Team</span>
            </div>
            <span className="text-[10px] font-mono text-muted-foreground">{internalDone}/{internalTasks.length}</span>
          </div>

          <div className="space-y-1.5 mb-3">
            {internalTasks.map((task) => (
              <div
                key={task.id}
                className={`group flex items-start gap-2.5 p-2.5 rounded-xl transition-colors ${
                  task.done ? "bg-emerald-50/50" : "hover:bg-muted/40"
                }`}
              >
                <button onClick={() => toggleTask(task.id)} className="flex-shrink-0 mt-0.5">
                  {task.done ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  ) : (
                    <Circle className="w-4 h-4 text-muted-foreground/40 hover:text-primary transition-colors" />
                  )}
                </button>
                <span
                  className={`flex-1 text-xs leading-relaxed ${
                    task.done ? "text-muted-foreground line-through" : "text-foreground"
                  }`}
                >
                  {task.text}
                  {task.autoGenerated && (
                    <span className="ml-1.5 text-[9px] font-mono text-muted-foreground/50">(auto)</span>
                  )}
                </span>
                <button
                  onClick={() => deleteTask(task.id)}
                  className="opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0 p-0.5 rounded hover:bg-red-50"
                >
                  <Trash2 className="w-3 h-3 text-muted-foreground hover:text-red-500" />
                </button>
              </div>
            ))}
            {internalTasks.length === 0 && (
              <p className="text-xs text-muted-foreground text-center py-4">No internal tasks yet. Add one below.</p>
            )}
          </div>

          {/* Add internal task */}
          <div className="border-t border-border pt-3 mt-1">
            <div className="flex gap-1.5 mb-1.5">
              <input
                value={newTaskType === "internal" ? newTaskText : ""}
                onChange={(e) => { setNewTaskType("internal"); setNewTaskText(e.target.value); }}
                onKeyDown={(e) => { if (e.key === "Enter") addTask(newTaskText, "internal"); }}
                placeholder="Add task…"
                className="flex-1 bg-input-background border border-border rounded-lg px-2.5 py-1.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
              <button
                onClick={() => addTask(newTaskText, "internal")}
                disabled={!newTaskText.trim() || newTaskType !== "internal"}
                className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-medium bg-[#7A9E9E] text-white hover:bg-[#7A9E9E]/90 disabled:bg-muted disabled:text-muted-foreground transition-colors"
              >
                <Plus className="w-3 h-3" />
              </button>
            </div>
            <button
              onClick={() => setShowPresets(showPresets === "internal" ? null : "internal")}
              className="text-[10px] font-mono text-muted-foreground hover:text-foreground transition-colors"
            >
              {showPresets === "internal" ? "Hide suggestions" : "Suggestions"}
            </button>
            {showPresets === "internal" && (
              <div className="flex flex-wrap gap-1 mt-2">
                {TASK_PRESETS.internal.map((preset) => (
                  <button
                    key={preset}
                    onClick={() => addPreset(preset, "internal")}
                    className="text-[10px] px-2 py-1 rounded-lg bg-muted text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors"
                  >
                    + {preset.length > 30 ? preset.slice(0, 30) + "…" : preset}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Save bar */}
      <div className="flex items-center gap-4">
        {saved ? (
          <div className="flex items-center gap-3 bg-emerald-50 border border-emerald-200 rounded-xl px-5 py-3">
            <CheckCircle2 className="w-5 h-5 text-emerald-600 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-emerald-800">Tasks saved</p>
              <p className="text-xs text-emerald-600">{clientTasks.length} client · {internalTasks.length} internal</p>
            </div>
            <button
              onClick={() => router.push(`/session-detail?sessionId=${sessionId}`)}
              className="ml-4 text-xs font-medium text-emerald-700 hover:underline"
            >
              View in history →
            </button>
          </div>
        ) : (
          <div className="flex items-center gap-3">
            <button
              onClick={handleSave}
              disabled={saving}
              className={`flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-medium transition-colors shadow-sm ${
                saving
                  ? "bg-muted text-muted-foreground cursor-not-allowed"
                  : "bg-primary text-primary-foreground hover:bg-primary/90"
              }`}
            >
              {saving ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Save className="w-4 h-4" />
              )}
              {saving ? "Saving…" : "Save to Client History"}
            </button>
            <button
              onClick={() => router.push(`/results?sessionId=${sessionId}`)}
              className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowRight className="w-3 h-3" />
              Back to Results
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default function NextStepsPage() {
  return (
    <Suspense fallback={
      <div className="flex-1 flex items-center justify-center p-8">
        <Loader2 className="w-6 h-6 text-primary animate-spin" />
      </div>
    }>
      <NextStepsInner />
    </Suspense>
  );
}
