import { NextRequest, NextResponse } from "next/server";
import { runPipeline } from "@/lib/pipeline";
import { saveSessionInput, saveSessionOutput, finalizeSession } from "@/lib/supabase/queries";
import { getSupabase } from "@/lib/supabase/client";
import type { PipelineOutput } from "@/lib/pipeline/types";
import type { ComputedStats } from "@/lib/pipeline/stats";
import type { TaskItem } from "@/types";

function generateTasks(output: PipelineOutput, stats: ComputedStats): TaskItem[] {
  const tasks: TaskItem[] = [];
  let id = 0;
  const nextId = () => `task_${++id}`;

  for (const flag of output.dataQualityFlags ?? []) {
    if (flag.severity === "danger") {
      tasks.push({ id: nextId(), text: `Provide complete data for "${flag.field}" — ${flag.issue}`, type: "client", done: false, autoGenerated: true });
      tasks.push({ id: nextId(), text: `Investigate data quality issue in "${flag.field}": ${flag.issue}`, type: "internal", done: false, autoGenerated: true });
    } else {
      tasks.push({ id: nextId(), text: `Review "${flag.field}": ${flag.issue}`, type: "internal", done: false, autoGenerated: true });
    }
  }

  for (const q of output.followUpQuestions ?? []) {
    tasks.push({ id: nextId(), text: q, type: "client", done: false, autoGenerated: true });
  }

  for (const a of output.recommendedAnalyses ?? []) {
    tasks.push({ id: nextId(), text: `Perform ${a.title} analysis`, type: "internal", done: false, autoGenerated: true });
  }

  for (const signal of output.keySignals ?? []) {
    tasks.push({ id: nextId(), text: `Validate signal: ${signal}`, type: "internal", done: false, autoGenerated: true });
  }

  for (const pair of stats.correlations.slice(0, 5)) {
    tasks.push({ id: nextId(), text: `Explore relationship between "${pair.colA}" and "${pair.colB}" (r = ${pair.r})`, type: "internal", done: false, autoGenerated: true });
  }

  for (const o of stats.outliers.slice(0, 5)) {
    tasks.push({ id: nextId(), text: `Review outlier in "${o.col}" (value ${o.value})`, type: "internal", done: false, autoGenerated: true });
  }

  return tasks;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { sessionId, csvContent, fileName, storagePath, briefText, businessGoal } = body;

    if (!sessionId || !csvContent || !fileName) {
      return NextResponse.json(
        { error: "Missing required fields: sessionId, csvContent, fileName" },
        { status: 400 }
      );
    }

    // Run the pipeline
    const { profile, output, stats } = runPipeline({
      csvContent,
      fileName,
      storagePath: storagePath ?? `uploads/${sessionId}/${fileName}`,
      briefText,
      businessGoal,
    });

    // Save session input
    await saveSessionInput(sessionId, {
      briefText: briefText ?? "",
      businessGoal: businessGoal ?? "",
      constraints: "",
      dataFiles: [
        {
          fileName: profile.fileName,
          fileType: "csv",
          fileUrl: storagePath ?? `uploads/${sessionId}/${fileName}`,
          rowCount: profile.rowCount,
          columnCount: profile.columnCount,
          sizeKb: profile.sizeKb,
          columns: profile.columns.map((c) => c.name),
          dtypes: Object.fromEntries(profile.columns.map((c) => [c.name, c.dtype])),
          nullPct: Object.fromEntries(profile.columns.map((c) => [c.name, c.nullPct])),
          sample: profile.sampleRows.slice(0, 5),
        },
      ],
    });

    // Auto-generate tasks from output + stats
    const tasks = generateTasks(output, stats);

    // Save session output
    await saveSessionOutput(sessionId, {
      execSummary: output.execSummary,
      keySignals: output.keySignals,
      dataQualityFlags: output.dataQualityFlags,
      recommendedAnalyses: output.recommendedAnalyses,
      followUpQuestions: output.followUpQuestions,
      assumptions: output.assumptions,
      confidenceScore: output.confidenceScore,
      dataCompleteness: output.dataCompleteness,
      statSummary: stats,
      tasks,
    });

    // Mark session as complete
    await finalizeSession(sessionId);

    // Populate session summary field for history view
    const sb = getSupabase();
    await sb.from("sessions").update({ summary: output.execSummary.slice(0, 300) }).eq("id", sessionId);

    return NextResponse.json({ sessionId, output, profile, stats });
  } catch (error: any) {
    console.error("Pipeline error:", error);
    return NextResponse.json(
      { error: error.message ?? "Pipeline execution failed" },
      { status: 500 }
    );
  }
}
