import { google } from "@ai-sdk/google";
import { generateText } from "ai";
import type { PipelineOutput } from "./types";
import type { ComputedStats } from "./stats";
import type { TaskItem } from "@/types";

const SYSTEM_PROMPT = `You are a senior data consultant. Based on a data analysis pipeline output, generate actionable next-step tasks.

Generate tasks in two categories:
- "client": tasks the client needs to do (provide data, clarify, review, etc.)
- "internal": tasks the internal data team needs to do (investigate, model, document, etc.)

Rules:
- Make each task specific, actionable, and concise (under 80 chars)
- Generate 4-8 client tasks and 6-12 internal tasks
- Cover data quality issues, analytical findings, outliers, correlations, and follow-ups
- Return ONLY valid JSON with no markdown, no code fences, no extra text
- Use this exact shape:
  {"tasks":[{"text":"...","type":"client|internal"}]}`;

export async function generateTasksLLM(
  output: PipelineOutput,
  stats: ComputedStats,
  briefText?: string,
  businessGoal?: string,
): Promise<TaskItem[]> {
  const geminiKey = process.env.GEMINI_API_KEY;
  if (!geminiKey) {
    throw new Error("GEMINI_API_KEY not set");
  }

  const input = JSON.stringify({
    execSummary: output.execSummary.slice(0, 2000),
    keySignals: output.keySignals,
    dataQualityFlags: output.dataQualityFlags,
    recommendedAnalyses: output.recommendedAnalyses,
    followUpQuestions: output.followUpQuestions,
    assumptions: output.assumptions,
    confidenceScore: output.confidenceScore,
    dataCompleteness: output.dataCompleteness,
    correlations: stats.correlations.slice(0, 10),
    distributions: stats.distributions.slice(0, 20),
    topValues: stats.topValues.slice(0, 20),
    outliers: stats.outliers.slice(0, 10),
    briefText: briefText?.slice(0, 1000),
    businessGoal,
  });

  const { text } = await generateText({
    model: google("gemini-2.0-flash-001"),
    system: SYSTEM_PROMPT,
    prompt: input,
    temperature: 0.4,
  });

  let parsed: { tasks: { text: string; type: string }[] };
  try {
    parsed = JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw new Error("LLM returned unparseable output: " + text.slice(0, 200));
    parsed = JSON.parse(match[0]);
  }

  const tasks: TaskItem[] = [];
  let id = 0;
  for (const t of (parsed.tasks ?? [])) {
    if (t.text && (t.type === "client" || t.type === "internal")) {
      tasks.push({
        id: `task_${++id}`,
        text: t.text,
        type: t.type,
        done: false,
        autoGenerated: true,
      });
    }
  }

  return tasks;
}
